-- 주차장(Parking Lots) 데이터 삽입
-- Generated by import_station_data.py

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '대구도시철도공사 칠곡가량기지환승주차장', '대구 북구 동호동136-1', ST_MakePoint(128.55905409649, 35.9607357165524)::geography, 310, NULL
FROM public.stations
WHERE name = '칠곡경대병원역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '동천주차빌딩주차장', '대구 북구 동천로 135-7', ST_MakePoint(128.55989529964097, 35.94368177206926)::geography, 70, NULL
FROM public.stations
WHERE name = '팔거역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '동천동복합청사 공영 주차장', '대구 북구 대천로 77', ST_MakePoint(128.557873149198, 35.9373449227825)::geography, 150, NULL
FROM public.stations
WHERE name = '동천역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '매천역 환승 공영주차장', '대구 북구 태전동 686-10', ST_MakePoint(128.54302461095, 35.913876537511)::geography, 120, '무료 (운영: 24시)'
FROM public.stations
WHERE name = '매천역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '서대구고속버스터미널 안 유료민영주차장', '대구 북구 팔달로 103', ST_MakePoint(128.561423768983, 35.8902436064382)::geography, 40, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '만평역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '제일민영주차장', '대구 서구 팔달로 164', ST_MakePoint(128.56608785271, 35.8722550306273)::geography, 40, '유료 (운영: 09:30-20:00)'
FROM public.stations
WHERE name = '팔달시장역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '드림유료주차장', '대구 북구 팔달로 217-1', ST_MakePoint(128.574080908864, 35.8882513761614)::geography, 60, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '원대역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '달성파크푸르지오힐스테이트 상가 주차장', '대구 중구 달성로 123', ST_MakePoint(128.578493787624, 35.8779018501669)::geography, 90, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '달성공원역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '계명대학교동산병원주차장', '대구 달서구 달구벌대로 1035', ST_MakePoint(128.583394129382, 35.867969362247)::geography, 20, NULL
FROM public.stations
WHERE name = '서문시장역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '척탑병원주차장', '대구 중구 달구벌대로 1999', ST_MakePoint(128.582701809564, 35.865456902865)::geography, 10, NULL
FROM public.stations
WHERE name = '청라언덕역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '계명유료주차장', '대구 중구 남산로 2', ST_MakePoint(128.583444206126, 35.8566863588604)::geography, 10, '유료'
FROM public.stations
WHERE name = '남산역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '성지교회민영주차장', '대구 중구 명덕로65길 10', ST_MakePoint(128.605295868779, 35.855702085764)::geography, 90, '유료 (운영: 08:00-20:00)'
FROM public.stations
WHERE name = '대봉교역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '에이콘유료주차장', '대구 수성구 명덕로 423', ST_MakePoint(128.616561575849, 35.8545094664364)::geography, 10, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '수성시장역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '진명유료주차장', '대구 수성구 명덕로 418', ST_MakePoint(128.615856103057, 35.854022609012)::geography, 10, '유료'
FROM public.stations
WHERE name = '수성시장역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '양정빌딩주차장', '대구 수성구 범어천로 52-1', ST_MakePoint(128.624086718493, 35.8515546790151)::geography, 220, '무료'
FROM public.stations
WHERE name = '수성구민운동장역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '대구한의사신협 유료주차장', '대구 수성구 동대구로 159', ST_MakePoint(128.623980538922, 35.8447527631777)::geography, 180, '유료'
FROM public.stations
WHERE name = '어린이세상역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '에이케이빌딩 주차장', '대구 수성구 동대구로 102', ST_MakePoint(128.624685585603, 35.8392738351518)::geography, 80, '정보없음 (운영: 08:30-19:00)'
FROM public.stations
WHERE name = '황금역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '광평빌딩주차장', '대구 수성구 동대구로 13', ST_MakePoint(128.622759312722, 35.8315621961079)::geography, 60, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '수성못역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '우리은행 범물동점 주차장', '대구 수성구 지범로 196', ST_MakePoint(128.640140006649, 35.8202845942006)::geography, 60, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '범물역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '설화명곡역 임시공영주차장', '대구 달성군 화암로 18', ST_MakePoint(128.488949199597, 35.7962840727236)::geography, 300, '무료 (운영: 24시)'
FROM public.stations
WHERE name = '설화명곡역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '상인공영주차장', '대구 달서구 상인서로 103-5', ST_MakePoint(128.539835849229, 35.8180638501001)::geography, 50, '유료 (운영: 06-23시)'
FROM public.stations
WHERE name = '상인역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '대구교통공사주차장', '대구 달서구 월배로 250', ST_MakePoint(128.5411469969618, 35.81949610446565)::geography, 50, '유료 (운영: 06-22시)'
FROM public.stations
WHERE name = '상인역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '관문시장 공영주차장', '대구 남구 관문시장 1길 36', ST_MakePoint(128.558983161339, 35.8360239045496)::geography, 180, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '서부정류장'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '남산공영주차장', '대구 중구 명덕로 35길 44', ST_MakePoint(128.589098950867, 35.8587023436223)::geography, 300, '유료 (운영: 08-22시)'
FROM public.stations
WHERE name = '명덕역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '메트로센터', '대구 중구 달구벌대로 2100', ST_MakePoint(128.593404958054, 35.8654399293326)::geography, 1, '유료 (운영: 06-24시)'
FROM public.stations
WHERE name = '반월당역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '경상감영주차장', '대구 중구 경상감영길 99', ST_MakePoint(128.59276239357132, 35.872717975731014)::geography, 50, '유료 (운영: 07-23시)'
FROM public.stations
WHERE name = '중앙로역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '교동공영주차장', '대구 중구 교동2길 11', ST_MakePoint(128.598361823771, 35.8736753941233)::geography, NULL, '유료 (운영: 08-22시)'
FROM public.stations
WHERE name = '대구역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '신천둔치주차장', '대구 북구 칠성동1가 276-1', ST_MakePoint(128.60468953830022, 35.87691892751881)::geography, 20, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '칠성시장역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '칠성공영주차장', '대구 북구 칠성남로 196', ST_MakePoint(128.6016525880039, 35.87615925500532)::geography, 90, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '칠성시장역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '신세계 동대구복합환승센터 주차장', '대구 동구 동부로 149', ST_MakePoint(128.629975678965, 35.8780625683005)::geography, 200, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '동대구역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '1주차장', '대구 동구 동대구로 550', ST_MakePoint(128.62901734648625, 35.88041402190937)::geography, 320, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '동대구역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '2주차장', '대구 동구 동대구로 550', ST_MakePoint(128.627499413207, 35.879988540372)::geography, 250, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '동대구역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '맞이주차방', '대구 동구 동대구로 550', ST_MakePoint(128.628775532684, 35.8794361440597)::geography, 120, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '동대구역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '아양교공영주차장', '대구 동구 효목동 5-24', ST_MakePoint(128.642038470026, 35.8867926172105)::geography, 150, '무료'
FROM public.stations
WHERE name = '아양교역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '방촌천복개주차장', '대구 동구 검사동 957-11', ST_MakePoint(128.65754521499832, 35.88471224246946)::geography, 80, '무료'
FROM public.stations
WHERE name = '해안역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '안심공영주차장', '대구 동구 괴전동 175-9', ST_MakePoint(128.7352901664, 35.8692482371084)::geography, 480, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '안심역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '대구한의대병원역 환승주차장', '대구 동구 사복동 610', ST_MakePoint(128.75039256992, 35.8715842941753)::geography, 10, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '대구한의대병원'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '하양역 환승주차장', '경북 경산시 하양읍 금락리 133-126', ST_MakePoint(128.817421916295, 35.9095595454958)::geography, 10, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '하양역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '문양역 환승주차장', '대구 달성군 문양리 1069-14', ST_MakePoint(128.437402369951, 35.8632915286604)::geography, 10, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '문양역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '달성군주차장', '대구 달성군 문양리 470', ST_MakePoint(128.480156077089, 35.7816495291295)::geography, 250, '무료'
FROM public.stations
WHERE name = '문양역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '성서행정타운 임시환승주차장', '대구 달서구 성서로 400', ST_MakePoint(128.507952465076, 35.8524238292505)::geography, 10, '무료 (운영: 24시)'
FROM public.stations
WHERE name = '성서산업단지역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '용산환승주차장', '대구 달서구 장기동 810-4', ST_MakePoint(128.529955286555, 35.8486022853142)::geography, 10, '유료 (운영: 07-18시)'
FROM public.stations
WHERE name = '용산역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '홈플러스주차장', '대구 달서구 달구벌대로 1467', ST_MakePoint(128.527403695401, 35.8494530018007)::geography, 10, '유료 (운영: 05-23:30)'
FROM public.stations
WHERE name = '용산역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '두류네거리 유료주차장', '대구 달서구 달구벌대로 1764', ST_MakePoint(128.55116733631, 35.8558891324795)::geography, 40, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '두류역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '두류공원2공영주차장', '대구 달서구 두류동 산154', ST_MakePoint(128.559280029728, 35.8522460951731)::geography, 780, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '반고개역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '서문주차빌딩', '대구 중구 큰장로 26길45', ST_MakePoint(128.580738000716, 35.8689090985327)::geography, 500, '유료 (운영: 07-22시)'
FROM public.stations
WHERE name = '청라언덕역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '시지근린공원주차장', '대구 수성구 달구벌대로 637길 5', ST_MakePoint(128.706264447444, 35.8414876102646)::geography, 150, '유료 (운영: 08-22시)'
FROM public.stations
WHERE name = '신매역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '계양주차장', '경북 경산시 계양동 732', ST_MakePoint(128.742429777758, 35.83292282725)::geography, 100, '무료'
FROM public.stations
WHERE name = '임당역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '임당환승주차장', '경북 경산시 임당동 875', ST_MakePoint(128.741613216749, 35.8353678885239)::geography, 20, '무료'
FROM public.stations
WHERE name = '임당역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '구미역사타워주차장', '경북 구미시 구미중앙로 76', ST_MakePoint(128.330939456358, 36.1283301167004)::geography, 10, '유료'
FROM public.stations
WHERE name = '구미역'
LIMIT 1;

INSERT INTO public.parking_lots (station_id, name, address, location, distance_to_station_m, fee_info)
SELECT id, '경산역전마을공영주차장', '경북 경산시 사정동 84-28', ST_MakePoint(128.727090958241, 35.8218091628794)::geography, 10, '유료 (운영: 24시)'
FROM public.stations
WHERE name = '경산역'
LIMIT 1;
